# Generated by Django 4.2.7 on 2023-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to=''),
        ),
    ]
